#!/usr/bin/env python3
import sys, os

_script_dir = os.path.abspath(os.path.dirname(__file__))
_submodule = os.path.join(_script_dir, 'moose_e5e72a5')
_sibling = os.path.join(os.path.dirname(_script_dir), 'moose_e5e72a5')
if os.path.exists(os.path.join(_submodule, 'framework', 'Makefile')):
  MOOSE_DIR = _submodule
elif os.path.exists(os.path.join(_sibling, 'framework', 'Makefile')):
  MOOSE_DIR = _sibling
else:
  MOOSE_DIR = _submodule
MOOSE_DIR = os.environ.get('MOOSE_DIR', MOOSE_DIR)

sys.path.append(os.path.join(MOOSE_DIR, 'python'))

from TestHarness import TestHarness
TestHarness.buildAndRun(sys.argv, 'farmsquakeworx', MOOSE_DIR)
