Content:
  - ${ROOT_DIR}/doc/content
  - ${MOOSE_DIR}/framework/doc/content
  - ${MOOSE_DIR}/modules/tensor_mechanics/doc/content

Renderer:
  type:                            MooseDocs.base.MaterializeRenderer

Extensions:
  MooseDocs.extensions.navigation:
    name:                          "FARMS QUAKEWORX"
    repo:                          https://github.com/chunhuizhao478/farmsquakeworx
    google-cse:                    008852834041008754713:g3ilnhhbbj9
    breadcrumbs:                   False
    scrollspy:                     False
    menu:                          !include ${ROOT_DIR}/doc/menu.yml
#   MooseDocs.extensions.bibtex:
  MooseDocs.extensions.katex:
    macros:                        !include ${ROOT_DIR}/doc/katex.macros.yml
  MooseDocs.extensions.appsyntax:
    executable:                    ${ROOT_DIR}
    remove:
      framework:                   !include ${MOOSE_DIR}/framework/doc/remove.yml
  MooseDocs.extensions.common:
    shortcuts:                     !include ${MOOSE_DIR}/framework/doc/globals.yml
  MooseDocs.extensions.acronym:
    acronyms:                      !include ${MOOSE_DIR}/framework/doc/acronyms.yml
  MooseDocs.extensions.template:
    active:                        True
  MooseDocs.extensions.sqa:
    active:                        False
